# Generated by Django 5.2.14 on 2026-05-26 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
