# Generated by Django 5.2.14 on 2026-05-25 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sketches',
            new_name='Sketch',
        ),
    ]
