# Generated by Django 5.2.14 on 2026-05-25 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0002_rename_sketches_sketch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='sketch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_v1.sketch'),
        ),
        migrations.AlterField(
            model_name='session',
            name='status',
            field=models.CharField(max_length=20),
        ),
    ]
