# Generated by Django 5.2.14 on 2026-05-26 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0002_master_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='master',
            name='phone_number',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
