# Generated by Django 5.2.14 on 2026-05-26 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0003_alter_client_phone_number_alter_master_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=models.CharField(default='+70000000000', max_length=16),
            preserve_default=False,
        ),
    ]
